-- EXP is not implemented for the moment, as the probably sole purpose of it would be to
-- act as a barrier for future ranked games (quite unlikely to happen, because there are
-- several other priorities, and time is what it is).
-- I'm against putting an experience system just to see people farming for no reason at all.
--
-- The formula we went for it was
-- xp = points > 4 and math.floor((points * 9.375) + (minutes * 12.5)) or 0
